spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    database: MYSQL

dbsource:
  food:
    url: "jdbc:mysql://ftk-rds-mysql.cuygjppbsrmy.ap-northeast-2.rds.amazonaws.com:3306/ftk_rds_mysql"
    username: "ftk_admin"
    password: "qlalfqjsgh1"
    driver-class-name: "com.mysql.jdbc.Driver"
    initial-size: 5
    test-on-borrow: true
    validation-query: "select 1 from dual"
    max-idle: 10
    min-idle: 1
    max-active: 10

logging.config: "classpath:logback.xml"
